In [1]:
pip install seaborn

Requirement already satisfied: seaborn in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
#step 1: LOAD DATASET
import seaborn  as sns
sidd=sns.load_dataset("tips")
print(sidd)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
#step 2:DATA UNDERSTADING
sidd.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [6]:
sidd.shape

(244, 7)

In [7]:
sidd.ndim

2

In [8]:
sidd.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [9]:
sidd.size

1708

In [10]:
sidd.size

1708

In [11]:
sidd.index

RangeIndex(start=0, stop=244, step=1)

In [12]:
sidd.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [13]:
sidd.nunique()

total_bill    229
tip           123
sex             2
smoker          2
day             4
time            2
size            6
dtype: int64

In [14]:
sidd.describe(include="all")

        total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [15]:
sidd.value_counts()

total_bill  tip   sex     smoker  day   time    size
13.00       2.00  Female  Yes     Thur  Lunch   2       2
16.99       1.01  Female  No      Sun   Dinner  2       1
10.34       1.66  Male    No      Sun   Dinner  3       1
21.01       3.50  Male    No      Sun   Dinner  3       1
23.68       3.31  Male    No      Sun   Dinner  2       1
                                                       ..
18.78       3.00  Male    Yes     Sat   Lunch   2       0
                                  Thur  Dinner  2       0
                                        Lunch   2       0
                                  Fri   Dinner  2       0
                                        Lunch   2       0
Name: count, Length: 7744, dtype: int64

In [16]:
sidd.axes

[RangeIndex(start=0, stop=244, step=1),
 Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')]

In [17]:
sidd.empty

False

In [18]:
sidd.T

,0,1,2,3,4,5,6,7,8,9,...,234,235,236,237,238,239,240,241,242,243
total_bill,16.99,10.34,21.01,23.68,24.59,25.29,8.77,26.88,15.04,14.78,...,15.53,10.07,12.6,32.83,35.83,29.03,27.18,22.67,17.82,18.78
tip,1.01,1.66,3.5,3.31,3.61,4.71,2.0,3.12,1.96,3.23,...,3.0,1.25,1.0,1.17,4.67,5.92,2.0,2.0,1.75,3.0
sex,Female,Male,Male,Male,Female,Male,Male,Male,Male,Male,...,Male,Male,Male,Male,Female,Male,Female,Male,Male,Female
smoker,No,No,No,No,No,No,No,No,No,No,...,Yes,No,Yes,Yes,No,No,Yes,Yes,No,No
day,Sun,Sun,Sun,Sun,Sun,Sun,Sun,Sun,Sun,Sun,...,Sat,Sat,Sat,Sat,Sat,Sat,Sat,Sat,Sat,Thur
time,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,...,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner
size,2,3,3,2,4,4,2,4,2,2,...,2,2,2,2,3,3,2,2,2,2

In [19]:
#step 3: DATA CLEANING
#1.check missing values
sidd.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
#2.fill miss values
#in case of any missing value by using a function "fillna"

In [ ]:
#3.delete missing value
#In case of any delete value by using a function"dropna()"

In [20]:
#4.Rename duplicate
sidd.drop_duplicates()

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[243 rows x 7 columns]

In [21]:
#5.Rename columns
sidd=sidd.rename(columns={"sex":"Gender"})
sidd=sidd.rename(columns={"total_bill":"Total_bill"})
sidd=sidd.rename(columns={"tip":"Tip"})
sidd=sidd.rename(columns={"smoker":"Smoker"})
sidd=sidd.rename(columns={"day":"Day"})
sidd=sidd.rename(columns={"time":"Time"})
sidd=sidd.rename(columns={"	size":"	Size"})
print(sidd)

     Total_bill   Tip  Gender Smoker   Day    Time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [22]:
# 6.Datatype conversion
sidd.dtypes

Total_bill     float64
Tip            float64
Gender        category
Smoker        category
Day           category
Time          category
size             int64
dtype: object

In [23]:
# 7.String operator
sidd["Gender"]=(sidd["Gender"]
            .str.replace("Female","F")
            .str.replace("Male","M"))
print(sidd["Gender"].to_string())

0      F
1      M
2      M
3      M
4      F
5      M
6      M
7      M
8      M
9      M
10     M
11     F
12     M
13     M
14     F
15     M
16     F
17     M
18     F
19     M
20     M
21     F
22     F
23     M
24     M
25     M
26     M
27     M
28     M
29     F
30     M
31     M
32     F
33     F
34     M
35     M
36     M
37     F
38     M
39     M
40     M
41     M
42     M
43     M
44     M
45     M
46     M
47     M
48     M
49     M
50     M
51     F
52     F
53     M
54     M
55     M
56     M
57     F
58     M
59     M
60     M
61     M
62     M
63     M
64     M
65     M
66     F
67     F
68     M
69     M
70     M
71     F
72     F
73     F
74     F
75     M
76     M
77     M
78     M
79     M
80     M
81     M
82     F
83     M
84     M
85     F
86     M
87     M
88     M
89     M
90     M
91     M
92     F
93     F
94     F
95     M
96     M
97     M
98     M
99     M
100    F
101    F
102    F
103    F
104    F
105    M
106    M
107    M
108    M
109    F
110    M
111    F
112    M
113    M
114    F
115    F
116    M
117    F
118    F
119    F
120    M
121    F
122    M
123    M
124    F
125    F
126    M
127    F
128    F
129    M
130    M
131    F
132    F
133    F
134    F
135    F
136    F
137    F
138    M
139    F
140    F
141    M
142    M
143    F
144    F
145    F
146    F
147    F
148    M
149    M
150    M
151    M
152    M
153    M
154    M
155    F
156    M
157    F
158    F
159    M
160    M
161    M
162    F
163    M
164    F
165    M
166    M
167    M
168    F
169    F
170    M
171    M
172    M
173    M
174    M
175    M
176    M
177    M
178    F
179    M
180    M
181    M
182    M
183    M
184    M
185    M
186    F
187    M
188    F
189    M
190    M
191    F
192    M
193    M
194    M
195    M
196    M
197    F
198    F
199    M
200    M
201    F
202    F
203    F
204    M
205    F
206    M
207    M
208    M
209    F
210    M
211    M
212    M
213    F
214    F
215    F
216    M
217    M
218    M
219    F
220    M
221    F
222    M
223    F
224    M
225    F
226    F
227    M
228    M
229    F
230    M
231    M
232    M
233    M
234    M
235    M
236    M
237    M
238    F
239    M
240    F
241    M
242    M
243    F

In [24]:
sidd
print(sidd["Day"].unique())

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

In [26]:
sidd["Day"] = sidd["Day"].astype(str)

day_map = {
    "Sun": "Sunday",
    "Sat": "Saturday",
    "Thur": "Thursday",
    "Fri": "Friday"
}

sidd["Day"] = sidd["Day"].replace(day_map)

print(sidd["Day"])

0        Sunday
1        Sunday
2        Sunday
3        Sunday
4        Sunday
         ...
239    Saturday
240    Saturday
241    Saturday
242    Saturday
243    Thursday
Name: Day, Length: 244, dtype: str

In [27]:
# Step 4:EDA
# 1.unique day
sidd["Day"].unique()

<StringArray>
['Sunday', 'Saturday', 'Thursday', 'Friday']
Length: 4, dtype: str

In [28]:
# unique time
sidd["Time"].unique

<bound method Series.unique of 0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: Time, Length: 244, dtype: category
Categories (2, str): ['Lunch', 'Dinner']>

In [29]:
sidd["Gender"].unique

<bound method Series.unique of 0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: Gender, Length: 244, dtype: str>

In [30]:
 #customer visited on each day
sidd.groupby("Day")[["Gender"]].value_counts()

Day       Gender
Friday    M         10
          F          9
Saturday  M         59
          F         28
Sunday    M         58
          F         18
Thursday  F         32
          M         30
Name: count, dtype: int64

In [31]:
# Average bill for each day
sidd.groupby("Day")[["Total_bill"]].mean()

          Total_bill
Day
Friday     17.151579
Saturday   20.441379
Sunday     21.410000
Thursday   17.682742

In [32]:
# Highest avg tip
sidd.groupby("Day")["Tip"].mean().sort_values()

Day
Friday      2.734737
Thursday    2.771452
Saturday    2.993103
Sunday      3.255132
Name: Tip, dtype: float64

In [33]:
sidd["Time"].value_counts()

Time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [34]:
sidd["Gender"].value_counts()

Gender
M    157
F     87
Name: count, dtype: int64

In [35]:
# Highest total sale
sidd.groupby("Day")["Total_bill"].sum().sort_values()

Day
Friday       325.88
Thursday    1096.33
Sunday      1627.16
Saturday    1778.40
Name: Total_bill, dtype: float64

In [36]:
# Machine Learning
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

sidd["Gender_encode"]=encoder.fit_transform(sidd["Gender"])
sidd["Smoker_encode"]=encoder.fit_transform(sidd["Smoker"])
sidd[["Smoker","Smoker_encode","Gender","Gender_encode"]]

    Smoker  Smoker_encode Gender  Gender_encode
0       No              0      F              0
1       No              0      M              1
2       No              0      M              1
3       No              0      M              1
4       No              0      F              0
..     ...            ...    ...            ...
239     No              0      M              1
240    Yes              1      F              0
241    Yes              1      M              1
242     No              0      M              1
243     No              0      F              0

[244 rows x 4 columns]

In [37]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\kathirvel\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
import pandas as pd

mugu= pd.DataFrame({
    "Gender": ["Male", "Female", "Female", "Male", "Male", "Female"],
    "Purchased": ["Yes", "No", "Yes", "No", "Yes", "No"]
})
mugu["Gender_encode"]=encoder.fit_transform(mugu["Gender"])
mugu["Purchased_encode"]=encoder.fit_transform(mugu["Purchased"])
sidd["Smoker_encode"]=encoder.fit_transform(sidd["Smoker"])

mugu[["Gender","Gender_encode"]]
mugu[["Purchased","Purchased_encode"]]
sidd[["Smoker","Gender_encode"]]

print(mugu)

   Gender Purchased  Gender_encode  Purchased_encode
0    Male       Yes              1                 1
1  Female        No              0                 0
2  Female       Yes              0                 1
3    Male        No              1                 0
4    Male       Yes              1                 1
5  Female        No              0                 0

In [39]:
mugu_day=pd.get_dummies(
    sidd,
    columns = ["Day"],
    dtype=int
)
print(mugu_day)

     Total_bill   Tip Gender Smoker    Time  size  Gender_encode  \
0         16.99  1.01      F     No  Dinner     2              0
1         10.34  1.66      M     No  Dinner     3              1
2         21.01  3.50      M     No  Dinner     3              1
3         23.68  3.31      M     No  Dinner     2              1
4         24.59  3.61      F     No  Dinner     4              0
..          ...   ...    ...    ...     ...   ...            ...
239       29.03  5.92      M     No  Dinner     3              1
240       27.18  2.00      F    Yes  Dinner     2              0
241       22.67  2.00      M    Yes  Dinner     2              1
242       17.82  1.75      M     No  Dinner     2              1
243       18.78  3.00      F     No  Dinner     2              0

     Smoker_encode  Day_Friday  Day_Saturday  Day_Sunday  Day_Thursday
0                0           0             0           1             0
1                0           0             0           1             0
2                0           0             0           1             0
3                0           0             0           1             0
4                0           0             0           1             0
..             ...         ...           ...         ...           ...
239              0           0             1           0             0
240              1           0             1           0             0
241              1           0             1           0             0
242              0           0             1           0             0
243              0           0             0           0             1

[244 rows x 12 columns]

In [40]:
day_mean=sidd.groupby("Day")["Tip"].mean()
print(day_mean)
sidd["day_encoded"]=sidd["Day"].map(day_mean)
sidd[["Day","day_encoded"]]

Day
Friday      2.734737
Saturday    2.993103
Sunday      3.255132
Thursday    2.771452
Name: Tip, dtype: float64

          Day  day_encoded
0      Sunday     3.255132
1      Sunday     3.255132
2      Sunday     3.255132
3      Sunday     3.255132
4      Sunday     3.255132
..        ...          ...
239  Saturday     2.993103
240  Saturday     2.993103
241  Saturday     2.993103
242  Saturday     2.993103
243  Thursday     2.771452

[244 rows x 2 columns]

In [42]:
from sklearn.preprocessing import StandardScaler

num_colm=["Total_bill","Tip","size"]
scaler=StandardScaler()

sidd[num_colm]=scaler.fit_transform(sidd[num_colm])

print(sidd.head())

   Total_bill       Tip Gender Smoker     Day    Time      size  \
0   -0.314711 -1.439947      F     No  Sunday  Dinner -0.600193
1   -1.063235 -0.969205      M     No  Sunday  Dinner  0.453383
2    0.137780  0.363356      M     No  Sunday  Dinner  0.453383
3    0.438315  0.225754      M     No  Sunday  Dinner -0.600193
4    0.540745  0.443020      F     No  Sunday  Dinner  1.506958

   Gender_encode  Smoker_encode  day_encoded
0              0              0     3.255132
1              1              0     3.255132
2              1              0     3.255132
3              1              0     3.255132
4              0              0     3.255132

In [43]:
from sklearn.preprocessing import MinMaxScaler

num_colm=["Total_bill","Tip","size"]
scaler=MinMaxScaler()

sidd[num_colm]=scaler.fit_transform(sidd[num_colm])

print(sidd.head())

   Total_bill       Tip Gender Smoker     Day    Time  size  Gender_encode  \
0    0.291579  0.001111      F     No  Sunday  Dinner   0.2              0
1    0.152283  0.073333      M     No  Sunday  Dinner   0.4              1
2    0.375786  0.277778      M     No  Sunday  Dinner   0.4              1
3    0.431713  0.256667      M     No  Sunday  Dinner   0.2              1
4    0.450775  0.290000      F     No  Sunday  Dinner   0.6              0

   Smoker_encode  day_encoded
0              0     3.255132
1              0     3.255132
2              0     3.255132
3              0     3.255132
4              0     3.255132

In [44]:
from sklearn.preprocessing import RobustScaler

num_colm=["Total_bill","Tip","size"]
scaler=RobustScaler()

sidd[num_colm]=scaler.fit_transform(sidd[num_colm])

print(sidd.head())

   Total_bill     Tip Gender Smoker     Day    Time  size  Gender_encode  \
0   -0.074675 -1.2096      F     No  Sunday  Dinner   0.0              0
1   -0.691558 -0.7936      M     No  Sunday  Dinner   1.0              1
2    0.298237  0.3840      M     No  Sunday  Dinner   1.0              1
3    0.545918  0.2624      M     No  Sunday  Dinner   0.0              1
4    0.630334  0.4544      F     No  Sunday  Dinner   2.0              0

   Smoker_encode  day_encoded
0              0     3.255132
1              0     3.255132
2              0     3.255132
3              0     3.255132
4              0     3.255132